version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__eventstore=Host=postgres;Database=event-store;Username=eventstore;Password=toor
      - ConnectionStrings__mongodb=mongodb://root:toor@mongo:27017
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - backend
      - frontend

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: toor
      POSTGRES_USER: eventstore
      POSTGRES_DB: event-store
    networks:
      - backend

  mongo:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    networks:
      - backend

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
    networks:
      - backend
      - frontend

networks:
  backend:
  frontend: