name: .NET Core
on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore Ealen.Dotnet.Templates.csproj
    - name: Build
      run: dotnet build Ealen.Dotnet.Templates.csproj --configuration Release --no-restore

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [
          "api/Api.Dotnet.Template",
          "api-cqrs/Dotnet.Cqrs.sln",
          "console/Console.Dotnet.Template"
        ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore ./templates/${{ matrix.project }}.sln
    - name: Build
      run: dotnet build ./templates/${{ matrix.project }}.sln --configuration Release --no-restore
    - name: Tests
      run: dotnet test ./templates/${{ matrix.project }}.sln --configuration Release --no-restore --collect:"XPlat Code Coverage"